/**************************************************************

Copyright Jan Marchant 2012
Licensed under the do whatever you want public license.

TERMS AND CONDITIONS OF THE DWYW PL:

1. Just DO WHATEVER YOU WANT.

Converts ITEX format as generated by the Hamamatsu streak camera
in Kobe to an ascii file.

This ITEX format differs slightly in the status string to the
specifications found online. Reading the scaling data may not
work with all .img files due to this.

Arguments:	<input file>
Outputs:	ascii table to standard output, status header to stderr.
To compile:	gcc main.c -o itex2ascii

*****************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>

int main(int argc, char ** argv)
{
	if (argc<2)
	{
		fprintf(stderr,"Usage: %s <input file>\n<input file> should be an ITEX format (.img) file as found in Kobe.\n",argv[0]);
		return 1;
	}

	FILE *input;

        if (!(input = fopen(argv[1], "r"))) {
                fprintf(stderr,"Couldn't open %s\n",argv[1]);
                return 1;
        }

	char IM[3];

	fread(IM,1,2,input);
	IM[2]=0;

	if (strcmp(IM,"IM")!=0) {
		fprintf(stderr,"This doesn't look like a valid ITEX (.img) file (first two bytes are %s, expected IM).\n",IM);
		fclose(input);
		return 1;
	}

	uint16_t header[6];

	fread(header,2,6,input);

	/***************************
	header[0] status length
	header[1] X pixels
	header[2] Y pixels
	header[3] X offset
	header[4] Y offset
	header[5] data type
		0=8 Bit, 1=Compressed (Not used by HPD-TA ), 2=16 Bit
	**************************/
	
	fseek(input,50,SEEK_CUR);

	char * status = calloc(header[0],sizeof(char));

	fread(status,1,header[0],input);

	//We only use the status to get axis info. This is not formatted as described in
	//the only reference available online, so this is just from trial and error!
	int i=0;
  	char * pch;
	char * xaxis;
        char * yaxis;
        char xscalesizemarker[2];
        char yscalesizemarker[2];
	int xscaleoffset;
        int yscaleoffset;

  	pch = strtok (status,",\n");
  	while (pch != NULL)
  	{
		if (i==48) {
			xaxis = calloc(strlen(pch)+1,sizeof(char));
			strcpy(xaxis,pch);
		}

                if (i==49) {
			strncpy(xscalesizemarker,pch,1);
			xscalesizemarker[1]=0;

                        xscaleoffset = atoi(pch+1);
                }

		if (i==52) {
                        yaxis = calloc(strlen(pch)+1,sizeof(char));
                        strcpy(yaxis,pch);
		}

                if (i==53) {
                        strncpy(yscalesizemarker,pch,1);
                        yscalesizemarker[1]=0;

                        yscaleoffset = atoi(pch+1);

                }
		if (i>70) {fprintf(stderr,"%s\n",pch);}
    		pch = strtok (NULL, ",\n");
		i++;
  	}	
	//fprintf(stdout,"%s %s %i %s %s %i\n",xaxis,xscalesizemarker,xscaleoffset,yaxis,yscalesizemarker,yscaleoffset);

	uint8_t * data8;
	uint16_t * data16;
	
	switch (header[5]) {
		case 0:
			{data8 = calloc(header[1]*header[2],8);
			fread(data8,1,header[1]*header[2],input);
			break;}
		case 2:
                        {data16 = calloc(header[1]*header[2],16);
		        fread(data16,2,header[1]*header[2],input);
                        break;}
		default:
			fprintf(stderr,"Oh no. Data type is not supported (%i)\n",header[5]);
			fclose(input);
			return 1;
	}

	if (ftell(input)!=xscaleoffset) {
		fprintf(stderr,"We're not in the right place. Expected offset %i, actual %li.\n",xscaleoffset,ftell(input));
	}
	
	float * xvalues = calloc(header[1],4);
	fread(xvalues,4,header[1],input);

	if (strcmp(xscalesizemarker,"*")==0) {
		fseek(input,4096+xscaleoffset,SEEK_SET);
	}

        if (strcmp(xscalesizemarker,"+")==0) {
                fseek(input,5120+xscaleoffset,SEEK_SET);
        }

        if (ftell(input)!=yscaleoffset) {
                fprintf(stderr,"We're not in the right place. Expected offset %i, actual %li.\n",yscaleoffset,ftell(input));
        }

        float * yvalues = calloc(header[2],4);
        fread(yvalues,4,header[2],input);

	int x;
	int y;

	fprintf(stdout,"#data parsed from %s\n#%s %s value\n",argv[1],xaxis,yaxis);
        switch (header[5]) {
                case 0:
                        {
                         for (y=0;y<header[2];y++) {
                                for (x=0;x<header[1];x++) {
                                        fprintf(stdout,"%g %g %"PRIu8"\n",xvalues[x],yvalues[y],data8[y*header[1]+x]);
                                }
				fprintf(stdout,"\n");
                         }
                         break;
                        }

                case 2:
			{
			 for (x=0;x<header[1];x++) {
				for (y=0;y<header[2];y++) {
					fprintf(stdout,"%g %g %"PRIu16"\n",xvalues[x],yvalues[y],data16[y*header[1]+x]);
				}
				fprintf(stdout,"\n");
			 }
			 break;
			}
	}

	fclose(input);

	return 0;
} 
